config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :restaurants do
    resources :reviews, except: [:show, :index]
    collection do
      get 'search'
    end
  end

  root 'restaurants#index'
  get 'pages/about', to: 'pages#about'
  get 'pages/contact', to: 'pages#contact'


end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :restaurants
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :state_provence, presence: true

  has_many :reviews
  belongs_to :category

  geocoded_by :full_address
  after_validation :geocode

  mount_uploader :image, ImageUploader

  def full_address
    [address1, address2, city, state_provence, postalcode].join(', ')
  end

  def self.search(params)
    restaurants = Restaurant.where(category_id: params[:category].to_i)

    restaurants = restaurants.where("name like ? or description like ?",
    "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?

    restaurants = restaurants.near(params[:location], 25) if params[:location].present?

    restaurants
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user

  validates :comment, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    [city, state_provence].join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :email, :password, :password_confirmation,
      :username, :first_name, :last_name, :latitude,
      :longitude, :city, :state_provence
    ])
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :email, :password, :password_confirmation,
      :username, :first_name, :last_name, :latitude,
      :longitude, :city, :state_provence
    ])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  def contact

  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @user = current_user

    if current_user
      @vlat = @user.latitude
      @vlon = @user.longitude

      visitor_latitude = @user.latitude
      visitor_longitude = @user.longitude

      @restaurants = Restaurant.near([visitor_latitude, visitor_longitude], 200)
      @fast_food_restaurants = Restaurant.where(category_id: 1).near([visitor_latitude, visitor_longitude], 200)
      @fast_food_search = Category.find(1)
      @seafood_restaurants = Restaurant.where(category_id: 2).near([visitor_latitude, visitor_longitude], 200)
      @seafood_search = Category.find(2)
      @steak_house_restaurants = Restaurant.where(category_id: 3).near([visitor_latitude, visitor_longitude], 200)
      @steak_house_search = Category.find(3)
      @chinese_restaurants = Restaurant.where(category_id: 4).near([visitor_latitude, visitor_longitude], 200)
      @chinese_search = Category.find(4)
      @family_restaurants = Restaurant.where(category_id: 5).near([visitor_latitude, visitor_longitude], 200)
      @family_search = Category.find(5)
      @coffee_restaurants = Restaurant.where(category_id: 6).near([visitor_latitude, visitor_longitude], 200)
      @coffee_search = Category.find(6)
     else
      visitor_latitude = 40.760779
      visitor_longitude = -111.8910470

      @vlat = visitor_latitude
      @vlon = visitor_longitude

      @restaurants = Restaurant.near([visitor_latitude, visitor_longitude], 200)
      @fast_food_restaurants = Restaurant.where(category_id: 1).near([visitor_latitude, visitor_longitude], 200)
      @fast_food_search = Category.find(1)
      @seafood_restaurants = Restaurant.where(category_id: 2).near([visitor_latitude, visitor_longitude], 200)
      @seafood_search = Category.find(2)
      @steak_house_restaurants = Restaurant.where(category_id: 3).near([visitor_latitude, visitor_longitude], 200)
      @steak_house_search = Category.find(3)
      @chinese_restaurants = Restaurant.where(category_id: 4).near([visitor_latitude, visitor_longitude], 200)
      @chinese_search = Category.find(4)
      @family_restaurants = Restaurant.where(category_id: 5).near([visitor_latitude, visitor_longitude], 200)
      @family_search = Category.find(5)
      @coffee_restaurants = Restaurant.where(category_id: 6).near([visitor_latitude, visitor_longitude], 200)
      @coffee_search = Category.find(6)
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = Review.where(restaurant_id: @restaurant)
    if @reviews.blank?
      @average_rating = 0
    else
      @average_rating = @reviews.average(:rating).round(2)
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @user = current_user
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:success] = "Awesome #{@user.username}! #{@restaurant.name} has been created successfully."
      redirect_to @restaurant
    else
      flash[:error] = "Sorry #{@user.username}, your restaurant was not created. Please see the error messages below."
      render :new
    end
  end

  def search
    @restaurants = Restaurant.search(params)
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :address1, :address2, :city, :state_provence, :postalcode, :phone, :website, :category_id, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant
  before_action :authenticate_user!

  def index
  end

  def new
    @review = Review.new(restaurant: @restaurant)
  end

  def create
    @review = current_user.reviews.build(review_params)
    @review.restaurant = @restaurant

    if @review.save
      flash[:success] = "Awesome #{current_user.first_name}! Your review has been saved."
      redirect_to @restaurant
    else
      flash[:error] = "There was a problem creating your review #{current_user.first_name}. Please try again."
      render :new
    end
  end

  private
    def review_params
      params.require(:review).permit(:comment, :rating)
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_header.html.erb
<header class="head-section">
  <div class="navbar navbar-default navbar-static-top container">
    <div class="navbar-header">
      <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <strong>R</strong><span><em>estaurant</em></span>
        <strong>R</strong><span><em>ank</em></span>
      <% end %>
    </div> <!-- end .navbar-header -->

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-close-others="false" data-delay="0" data-hover="dropdown" data-toggle="dropdown" href="#"><%= current_user.username %> <i class="fa fa-angle-down"></i>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, data: { close_others: false, delay: 0, hover: 'dropdown' }, method: :delete do %>
                <i class="fa fa-sign-out"></i> Sign Out
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path, data: { close_others: false, delay: 0, hover: 'dropdown' } do %>
                <i class="fa fa-edit"></i> Edit My Profile
              <% end %>
            </li>
            <% else %>
            <li>
              <%= link_to new_user_session_path, data: { close_others: false, delay: 0, hover: 'dropdown' } do %>
                <i class="fa fa-sign-in"></i> Sign In
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, data: { close_others: false, delay: 0, hover: 'dropdown' } do %>
                <i class="fa fa-pencil"></i> Sign Up
              <% end %>
            </li>
            <% end %>
          </ul>  <!-- end .dropdown-menu -->
        </li>  <!-- end .dropdown -->
      </ul> <!-- end .nav -->
    </div>  <!-- end .navbar-collapse -->
    
  </div>  <!-- end .navbar -->
</header>

app/views/layouts/_script.html.erb
<script src="js/jquery-1.8.3.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/hover-dropdown.js"></script>
<script defer src="js/jquery.flexslider.js"></script>
<script type="text/javascript" src="assets/bxslider/jquery.bxslider.js"></script>

<script type="text/javascript" src="js/jquery.parallax-1.1.3.js"></script>
<script src="js/wow.min.js"></script>
<script src="assets/owlcarousel/owl.carousel.js"></script>

<script src="js/jquery.easing.min.js"></script>
<script src="js/link-hover.js"></script>
<script src="js/superfish.js"></script>
<script type="text/javascript" src="js/parallax-slider/jquery.cslider.js"></script>

<script type="text/javascript">
  $(function() {
    $('#da-slider').cslider({
      autoplay    : true,
      bgincrement : 100
    });
  });
</script>

<script src="js/common-scripts.js"></script>

<script type="text/javascript">
  jQuery(document).ready(function() {
    $('.bxslider1').bxSlider({
      minSlides: 5,
      maxSlides: 6,
      slideWidth: 360,
      slideMargin: 2,
      moveSlides: 1,
      responsive: true,
      nextSelector: '#slider-next',
      prevSelector: '#slider-prev',
      nextText: 'Onward →',
      prevText: '← Go back'
    });
  });
</script>

<script>
  $('a.info').tooltip();
  $(window).load(function() {
    $('.flexslider').flexslider({
      animation: "slide",
      start: function(slider) {
        $('body').removeClass('loading');
      }
    });
  });

  $(document).ready(function() {
    $("#owl-demo").owlCarousel({
      items : 4
    });
  });

  jQuery(document).ready(function(){
    jQuery('ul.superfish').superfish();
  });

  new WOW().init();
</script>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/restaurants/_categories.html.erb
<div class="row span12 text-center">
  <div class="col-md-4">
    <h4><strong>Fast Food</strong></h4>
    <% @fast_food_restaurants.limit(4).each do |restaurant| %>
      <ul class='restaurant_li'>
        <li><%= link_to restaurant.name, restaurant %></li>
      </ul>
    <% end %>
    <%= link_to 'See All', search_restaurants_path(category: @fast_food_search.id), class: 'btn btn-info btn-xs' %>
  </div>
  <div class="col-md-4">
    <h4><strong>Seafood</strong></h4>
    <% @seafood_restaurants.limit(4).each do |restaurant| %>
      <ul class='restaurant_li'>
        <li><%= link_to restaurant.name, restaurant %></li>
      </ul>
    <% end %>
    <%= link_to 'See All', search_restaurants_path(category: @seafood_search.id), class: 'btn btn-info btn-xs' %>
  </div>
  <div class="col-md-4">
    <h4><strong>Steak House</strong></h4>
    <% @steak_house_restaurants.limit(4).each do |restaurant| %>
      <ul class='restaurant_li'>
        <li><%= link_to restaurant.name, restaurant %></li>
      </ul>
    <% end %>
    <%= link_to 'See All', search_restaurants_path(category: @steak_house_search.id), class: 'btn btn-info btn-xs' %>
  </div>
</div>
<hr>
<div class="row span12 text-center">
  <div class="col-md-4">
    <h4><strong>Chinese</strong></h4>
    <% @chinese_restaurants.limit(4).each do |restaurant| %>
      <ul class='restaurant_li'>
        <li><%= link_to restaurant.name, restaurant %></li>
      </ul>
    <% end %>
    <%= link_to 'See All', search_restaurants_path(category: @chinese_search.id), class: 'btn btn-info btn-xs' %>
  </div>
  <div class="col-md-4">
    <h4><strong>Family</strong></h4>
    <% @family_restaurants.limit(4).each do |restaurant| %>
      <ul class='restaurant_li'>
        <li><%= link_to restaurant.name, restaurant %></li>
      </ul>
    <% end %>
    <%= link_to 'See All', search_restaurants_path(category: @family_search.id), class: 'btn btn-info btn-xs' %>
  </div>
  <div class="col-md-4">
    <h4><strong>Coffee</strong></h4>
    <% @coffee_restaurants.limit(4).each do |restaurant| %>
      <ul class='restaurant_li'>
        <li><%= link_to restaurant.name, restaurant %></li>
      </ul>
    <% end %>
    <%= link_to 'See All', search_restaurants_path(category: @coffee_search.id), class: 'btn btn-info btn-xs' %>
  </div>
</div>
<br>

app/views/restaurants/index.html.erb
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h1>
          Restaurants
        </h1>
      </div>
    </div>
  </div>
</div>

<%= render 'restaurants/slider' %>

<br>

<div class="container">
  <%= link_to "Create a Restaurant", new_restaurant_path, class: 'btn btn-primary' %>

  <br />
  <br>

  <%= form_tag search_restaurants_path, method: :get do |f| %>
    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= text_field_tag :search, nil, placeholder: 'What are you hungry for?', class: 'form-control' %>
        </div>
      </div>

      <div class="col-md-4">
        <div class="form-group">
          <%= text_field_tag :location, nil, placeholder: 'Where do you want to eat?', class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= select_tag :category, options_for_select(Category.all.map { |category| [category.name, category.id] }) %>
    </div>

    <%= submit_tag 'Search', class: 'btn btn-info' %>
  <% end %>
  <hr>

  <%= render 'restaurants/categories' %>

</div>

<div class="contact-map">
    <div id="map-canvas" style="width: 100%; height: 400px">
    </div>
</div>

<script src="js/jquery.js">
</script>
<script src="js/bootstrap.min.js">
</script>
<script type="text/javascript" src="js/hover-dropdown.js">
</script>
<script type="text/javascript" src="assets/bxslider/jquery.bxslider.js">
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCIeQs2vvpfm_w7LJyO6dcc3k-y2oT_enY&v=3.exp&AMP">
</script>

<script>
  //google map
  function initialize() {
    var myLatlng = new google.maps.LatLng(<%= @vlat %>, <%= @vlon %>);
    var mapOptions = {
      zoom: 12,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
      var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
      var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'Contact'
    });
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/restaurants/show.html.erb
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>
          <%= @restaurant.name %> (<%= @restaurant.city %>, <%= @restaurant.state_provence %>)
        </h1>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="pf-img text-center">
        <% if @restaurant.image_url.present? %>
          <%= image_tag @restaurant.image_url(:restaurant_show) %>
        <% else %>
          <%= image_tag 'restaurant_show_dummy.png' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- begin:content -->
<div id="content">
  <div class="container">
    <div class="row">
      <!-- begin:article -->
      <div class="col-md-9 col-md-push-3">
        <div class="row">
          <div class="col-md-12 single-post">
            <ul id="myTab" class="nav nav-tabs nav-justified">
              <p>
              <li>
                <% if @reviews.blank? %>
                  This establishment has no reviews. Be the first to add a review.
                <% else %>
                  <strong><%= @restaurant.name %></strong>
                  has an average rating of
                  <strong><em>(<%= @average_rating %>)</em></strong> stars
                  <span class="star-rating" data-score=<%= @average_rating %>></span>
                  and has been reviewed by <%= @reviews.count %> <%= "client".pluralize @reviews.count %>.
                <% end %>
              </li>
            </p>
            </ul>

            <div id="myTabContent" class="tab-content">
              <div class="tab-pane fade in active" id="detail">
                <div class="row">
                  <div class="col-md-12">
                    <h2><%= @restaurant.name.titleize %></h2>

                    <h3 class="text-muted">Restaurant Overview</h3>
                    <table class="table table-bordered">
                    <tr>
                      <td><strong>Restaurant Name</strong></td>
                      <td><%= @restaurant.name.titleize %></td>
                    </tr>
                    <tr>
                      <td><strong>Website</strong></td>
                      <td>
                        <% if @restaurant.website.present? %>
                          <%= link_to @restaurant.website, 'http://' + @restaurant.website, target: '_blank' %>
                        <% end %>
                      </td>
                    </tr>
                    <tr>
                      <td><strong>Address</strong></td>
                      <td><%= @restaurant.address1 %>
                        <% if @restaurant.address2.present? %>
                        , <span><%= @restaurant.address2 %></span>
                        <% end %>
                      </td>
                    </tr>
                    <tr>
                      <td><strong>City, State/Provence  Postal Code </strong></td>
                      <td><%= @restaurant.city.titleize %>,
                        <span>
                          <%= @restaurant.state_provence.upcase %>
                        </span>
                        <span>
                        <%= @restaurant.postalcode %>
                        </span>
                      </td>
                    </tr>
                    <tr>
                      <td><strong>Telephone</strong></td>
                      <td><%= @restaurant.phone %></td>
                    </tr>
                    </table>
                    <h3></h3>
                    <!-- <div class="row">
                      <div class="col-md-4 col-sm-4">
                        <ul>
                          <li><i class="fa fa-check"></i> Air conditioning</li>
                          <li><i class="fa fa-check"></i> Balcony</li>
                          <li><i class="fa fa-times"></i> Bedding</li>
                          <li><i class="fa fa-check"></i> Cable TV</li>
                          <li><i class="fa fa-times"></i> Cleaning after exit</li>
                          <li><i class="fa fa-check"></i> Cofee pot</li>
                          <li><i class="fa fa-check"></i> Computer</li>
                          <li><i class="fa fa-times"></i> Cot</li>
                        </ul>
                      </div>
                      <div class="col-md-4 col-sm-4">
                        <ul>
                          <li><i class="fa fa-check"></i> Internet</li>
                          <li><i class="fa fa-times"></i> Iron</li>
                          <li><i class="fa fa-check"></i> Juicer</li>
                          <li><i class="fa fa-times"></i> Lift</li>
                          <li><i class="fa fa-times"></i> Microwave</li>
                          <li><i class="fa fa-check"></i> Oven</li>
                          <li><i class="fa fa-times"></i> Parking</li>
                          <li><i class="fa fa-times"></i> Parquet</li>
                        </ul>
                      </div>
                      <div class="col-md-4 col-sm-4">
                        <ul>
                          <li><i class="fa fa-times"></i> Radio</li>
                          <li><i class="fa fa-check"></i> Roof terrace</li>
                          <li><i class="fa fa-times"></i> Smoking allowed</li>
                          <li><i class="fa fa-check"></i> Terrace</li>
                          <li><i class="fa fa-times"></i> Toaster</li>
                          <li><i class="fa fa-check"></i> Towelwes</li>
                          <li><i class="fa fa-check"></i> Use of pool</li>
                          <li><i class="fa fa-check"></i> Video</li>
                        </ul>
                      </div>
                    </div> -->

                    <!-- <h3>Property Description</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat.</p> -->

                    <h2>More about <%= @restaurant.name %></h2>
                    <p><%= @restaurant.description %></p>
                  </div>
                  <div class="contact-map">
                      <div id="map-canvas" style="width: 100%; height: 400px">
                      </div>
                  </div>
                </div>
              </div>
              <!-- break -->
              <div class="tab-pane fade" id="location">
                <div class="row">
                  <div class="col-md-12">
                    <div id="map-property"></div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <h3>Contact Agent</h3>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6 col-sm-6">
                    <div class="team-container team-dark">
                      <div class="team-image">
                        <img src="img/team01.jpg" alt="the team - mikha realestate theme">
                      </div>
                      <div class="team-description">
                        <h3>Katty Sharon</h3>
                        <p><i class="fa fa-phone"></i> Office : 021-234-5678<br>
                        <i class="fa fa-mobile"></i> Mobile : +62-3456-78910<br>
                        <i class="fa fa-print"></i> Fax : 021-234-5679</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua.</p>
                        <div class="team-social">
                          <span><a href="#" title="Twitter" rel="tooltip" data-placement="top"><i class="fa fa-twitter"></i></a></span>
                          <span><a href="#" title="Facebook" rel="tooltip" data-placement="top"><i class="fa fa-facebook"></i></a></span>
                          <span><a href="#" title="Google Plus" rel="tooltip" data-placement="top"><i class="fa fa-google-plus"></i></a></span>
                          <span><a href="#" title="Email" rel="tooltip" data-placement="top"><i class="fa fa-envelope"></i></a></span>
                          <span><a href="#" title="LinkedIn" rel="tooltip" data-placement="top"><i class="fa fa-linkedin"></i></a></span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6 col-sm-6">
                    <form>
                      <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control input-lg" placeholder="Enter name : ">
                      </div>
                      <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control input-lg" placeholder="Enter email : ">
                      </div>
                      <div class="form-group">
                        <label for="telp">Telp.</label>
                        <input type="text" class="form-control input-lg" placeholder="Enter phone number : ">
                      </div>
                      <div class="form-group">
                        <label for="message">Message</label>
                        <textarea class="form-control input-lg" rows="7" placeholder="Type a message : "></textarea>
                      </div>
                      <div class="form-group">
                        <input type="submit" name="submit" value="Send Message" class="btn btn-success btn-lg">
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-md-pull-9 sidebar">
        <!-- <div class="widget-white favorite">
          <a href="#"><i class="fa fa-heart"></i> Add to favorite</a>
        </div> -->
        <div class="widget widget-sidebar widget-white">
          <div class="widget-header">
            <h3>Restaurant Reviews</h3>
          </div>
          <% @reviews.each do |review| %>
            <blockquote class="blockquote">
              <span class="star-rating" data-score=<% review.rating %>></span><br />
              <p><%= review.comment %></p>
              <p class="m-b-0"></p>
              <footer class="blockquote-footer pull-right">
                <cite><%= review.user.username %></cite>
              </footer>
            </blockquote>
            <hr>
          <% end %>
        </div>
        <br />
        <%= link_to "Create Review", new_restaurant_review_path(@restaurant), class: "btn btn-info" %>
        <div class="widget widget-sidebar widget-white">
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal-signup" tabindex="-1" role="dialog" aria-labelledby="modal-signup" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Sign up</h4>
      </div>
      <div class="modal-body">
        <form role="form">
          <div class="form-group">
            <input type="email" class="form-control input-lg" placeholder="Enter email">
          </div>
          <div class="form-group">
            <input type="password" class="form-control input-lg" placeholder="Password">
          </div>
          <div class="form-group">
            <input type="password" class="form-control input-lg" placeholder="Confirm Password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox" name="agree"> Agree to our <a href="#">terms of use</a> and <a href="#">privacy policy</a>
            </label>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<script src="js/jquery.js">
</script>
<script src="js/bootstrap.min.js">
</script>
<script type="text/javascript" src="js/hover-dropdown.js">
</script>
<script type="text/javascript" src="assets/bxslider/jquery.bxslider.js">
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCIeQs2vvpfm_w7LJyO6dcc3k-y2oT_enY&v=3.exp&AMP">
</script>

<script>
  //google map
  function initialize() {
    var myLatlng = new google.maps.LatLng(<%= @restaurant.latitude %>, <%= @restaurant.longitude %>);
    var mapOptions = {
      zoom: 15,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
      var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
      var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'Contact'
    });
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/reviews/index.html.erb
Hello from reviews